/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxy;

import java.util.Scanner;

import main.java.proxy.FileDataProxy;
import main.java.proxy.FileDataUtil;


/**
 * 
 * proxy pattern ex
 * 
 * 파일명 입력 시 해당파일의 데이터 로드하여 캐싱하는 예제 프로그램.
 * 동일한 파일을 다시불러오게되면 캐싱된 데이터로 불러오게 한다.
 * 
 */
public class App {
    

    public static void main(String[] args) {
        
        Scanner sc = new Scanner(System.in);
        String inputStr = "";
        StringBuilder contents = new StringBuilder("");

        FileDataProxy fdP = new FileDataProxy(new FileDataUtil());

        while(true){

            System.out.print("input fileName : ");

            inputStr = sc.nextLine();

            contents.append(fileDataToStr(fdP.getFileData(inputStr)));

            System.out.println("file Contents >> " + contents);

            contents.delete(0, contents.length());

        }
        
    }


    static String fileDataToStr(byte[] fileData){
        return fileData == null ? "" : new String(fileData);
    }
}
